# FILL DISTRICT

# 1. Автономна республіка Крим
INSERT INTO District VALUES (1, "Алушта, місто",1,1);
INSERT INTO District VALUES (2, "Бахчисарайський район",2,1);
INSERT INTO District VALUES (3, "Білогірський район",3,1);
INSERT INTO District VALUES (4, "Джанкойський район",4,1);
INSERT INTO District VALUES (5, "Євпаторія, місто",5,1);
INSERT INTO District VALUES (6, "Керч, місто",6,1);
INSERT INTO District VALUES (7, "Кіровський район",7,1);
INSERT INTO District VALUES (8, "Красногвардійський район",8,1);
INSERT INTO District VALUES (9, "Красноперекопський район",9,1);
INSERT INTO District VALUES (10, "Ленінський район",10,1);
INSERT INTO District VALUES (11, "Нижньогірський район",11,1);
INSERT INTO District VALUES (12, "Первомайський район",12,1);
INSERT INTO District VALUES (13, "Роздольненський район",13,1);
INSERT INTO District VALUES (14, "Сакський район",14,1);
INSERT INTO District VALUES (15, "Сімферополь, місто",15,1);
INSERT INTO District VALUES (16, "Сімферопольський район",16,1);
INSERT INTO District VALUES (17, "Совєтський район",17,1);
INSERT INTO District VALUES (18, "Судак, місто",18,1);
INSERT INTO District VALUES (19, "Феодосія, місто",19,1);
INSERT INTO District VALUES (20, "Чорноморський район",20,1);
INSERT INTO District VALUES (21, "Ялта, місто",21,1);

# 2. Вінницька область
INSERT INTO District VALUES (22, "Барський район",1,2);
INSERT INTO District VALUES (23, "Бершадський район",2,2);
INSERT INTO District VALUES (24, "Вінниця, місто",3,2);
INSERT INTO District VALUES (25, "Вінницький район",4,2);
INSERT INTO District VALUES (26, "Гайсинський район",5,2);
INSERT INTO District VALUES (27, "Жмеринський район",6,2);
INSERT INTO District VALUES (28, "Іллінецький район",7,2);
INSERT INTO District VALUES (29, "Калинівський район",8,2);
INSERT INTO District VALUES (30, "Козятинський район",9,2);
INSERT INTO District VALUES (31, "Крижопільський район",10,2);
INSERT INTO District VALUES (32, "Липовецький район",11,2);
INSERT INTO District VALUES (33, "Літинський район",12,2);
INSERT INTO District VALUES (34, "Могилів-Подільський район",13,2);
INSERT INTO District VALUES (35, "Мурованокуриловецький район",14,2);
INSERT INTO District VALUES (36, "Немирівський район",15,2);
INSERT INTO District VALUES (37, "Оратівський район",16,2);
INSERT INTO District VALUES (38, "Піщанський район",17,2);
INSERT INTO District VALUES (39, "Погребищенський район",18,2);
INSERT INTO District VALUES (40, "Теплицький район",19,2);
INSERT INTO District VALUES (41, "Тиврівський район",20,2);
INSERT INTO District VALUES (42, "Томашпільський район",21,2);
INSERT INTO District VALUES (43, "Тростянецький район",22,2);
INSERT INTO District VALUES (44, "Тульчинський район",23,2);
INSERT INTO District VALUES (45, "Хмільницький район",24,2);
INSERT INTO District VALUES (46, "Чернівецький район",25,2);
INSERT INTO District VALUES (47, "Чечельницький район",26,2);
INSERT INTO District VALUES (48, "Шаргородський район",27,2);
INSERT INTO District VALUES (49, "Ямпільський район",28,2);

# 3. Волинська область
INSERT INTO District VALUES (50, "Володимир-Волинський район",1,3);
INSERT INTO District VALUES (51, "Горохівський район",2,3);
INSERT INTO District VALUES (52, "Іваничівський район",3,3);
INSERT INTO District VALUES (53, "Камінь-Каширський район",4,3);
INSERT INTO District VALUES (54, "Ківерцівський район",5,3);
INSERT INTO District VALUES (55, "Ковельський район",6,3);
INSERT INTO District VALUES (56, "Локачинський район",7,3);
INSERT INTO District VALUES (57, "Луцьк, місто",8,3);
INSERT INTO District VALUES (58, "Луцький район",9,3);
INSERT INTO District VALUES (59, "Любешівський район",10,3);
INSERT INTO District VALUES (60, "Любомльський район",11,3);
INSERT INTO District VALUES (61, "Маневицький район",12,3);
INSERT INTO District VALUES (62, "Нововолинськ, місто",13,3);
INSERT INTO District VALUES (63, "Ратнівський район",14,3);
INSERT INTO District VALUES (64, "Рожищенський район",15,3);
INSERT INTO District VALUES (65, "Старовижівський район",16,3);
INSERT INTO District VALUES (66, "Турійський район",17,3);
INSERT INTO District VALUES (67, "Щацький район",18,3);

# 4. Дніпропетровська область
INSERT INTO District VALUES (68, "Апостолівський район",1,4);
INSERT INTO District VALUES (69, "Васильківський район",2,4);
INSERT INTO District VALUES (70, "Верхньодніпровський район",3,4);
INSERT INTO District VALUES (71, "Вільногірськ, місто",4,4);
INSERT INTO District VALUES (72, "Дніпродзержинськ, місто",5,4);
INSERT INTO District VALUES (73, "Дніпропетровськ, місто",6,4);
INSERT INTO District VALUES (74, "Дніпропетровський район",7,4);
INSERT INTO District VALUES (75, "Жовті води, місто",8,4);
INSERT INTO District VALUES (76, "Кривий ріг, місто",9,4);
INSERT INTO District VALUES (77, "Криворізький район",10,4);
INSERT INTO District VALUES (78, "Криничанський район",11,4);
INSERT INTO District VALUES (79, "Магдалинівський район",12,4);
INSERT INTO District VALUES (80, "Марганець, місто",13,4);
INSERT INTO District VALUES (81, "Межівський район",14,4);
INSERT INTO District VALUES (82, "Нікопольський район",15,4);
INSERT INTO District VALUES (83, "Новомосковський район",16,4);
INSERT INTO District VALUES (84, "Орджонікідзе, місто",17,4);
INSERT INTO District VALUES (85, "Павлоградський район",18,4);
INSERT INTO District VALUES (86, "Першотравенськ, місто",19,4);
INSERT INTO District VALUES (87, "Петриківський район",20,4);
INSERT INTO District VALUES (88, "Петропавлівський район",21,4);
INSERT INTO District VALUES (89, "Покровський район",22,4);
INSERT INTO District VALUES (90, "П'ятихатський район",23,4);
INSERT INTO District VALUES (91, "Синельниківський район",24,4);
INSERT INTO District VALUES (92, "Солонянський район",25,4);
INSERT INTO District VALUES (93, "Софіївський район",26,4);
INSERT INTO District VALUES (94, "Тернівка, місто",27,4);
INSERT INTO District VALUES (95, "Томаківський район",28,4);
INSERT INTO District VALUES (96, "Царичанський район",29,4);
INSERT INTO District VALUES (97, "Широківський район",30,4);
INSERT INTO District VALUES (98, "Юр'ївський район",31,4);

# 5. Донецька область
INSERT INTO District VALUES(99, "Амвросіївський район",1,5);
INSERT INTO District VALUES(100, "Артемівський район",2,5);
INSERT INTO District VALUES(101, "Великоновосілківський район",3,5);
INSERT INTO District VALUES(102, "Волноваський район",4,5);
INSERT INTO District VALUES(103, "Володарський район",5,5);
INSERT INTO District VALUES(104, "Горлівка, місто",6,5);
INSERT INTO District VALUES(105, "Дебальцеве, місто",7,5);
INSERT INTO District VALUES(106, "Дзержинськ, місто",8,5);
INSERT INTO District VALUES(107, "Добропільський район",9,5);
INSERT INTO District VALUES(108, "Донецьк, місто",10,5);
INSERT INTO District VALUES(109, "Дружківка, місто",11,5);
INSERT INTO District VALUES(110, "Єнакієве, місто",12,5);
INSERT INTO District VALUES(111, "Кіровське, місто",13,5);
INSERT INTO District VALUES(112, "Костянтинівський район",14,5);
INSERT INTO District VALUES(113, "Краматорськ, місто",15,5);
INSERT INTO District VALUES(114, "Красноармійський район",16,5);
INSERT INTO District VALUES(115, "Краснолиманський район",17,5);
INSERT INTO District VALUES(116, "Макіївка, місто",18,5);
INSERT INTO District VALUES(117, "Мангуський район",19,5);
INSERT INTO District VALUES(118, "Мар'їнський район",20,5);
INSERT INTO District VALUES(119, "Маріуполь, місто",21,5);
INSERT INTO District VALUES(120, "Новоазовський район",22,5);
INSERT INTO District VALUES(121, "Олександрівський район",23,5);
INSERT INTO District VALUES(122, "Селидове, місто",24,5);
INSERT INTO District VALUES(123, "Слов'янський район",25,5);
INSERT INTO District VALUES(124, "Сніжне, місто",26,5);
INSERT INTO District VALUES(125, "Старобешівський район",27,5);
INSERT INTO District VALUES(126, "Тельманівський район",28,5);
INSERT INTO District VALUES(127, "Торез, місто",29,5);
INSERT INTO District VALUES(128, "Харцизьк, місто",30,5);
INSERT INTO District VALUES(129, "Шахтарський район",31,5);
INSERT INTO District VALUES(130, "Ясинуватський район",32,5);

# 6. Житомирська область
INSERT INTO District VALUES(131,"Андрушівський район",1,6);
INSERT INTO District VALUES(132,"Баранівський район",2,6);
INSERT INTO District VALUES(133,"Бердичівський район",3,6);
INSERT INTO District VALUES(134,"Брусилівський район",4,6);
INSERT INTO District VALUES(135,"Володарсько-Волинський район",5,6);
INSERT INTO District VALUES(136,"Дзержинський район",6,6);
INSERT INTO District VALUES(137,"Ємільчинський район",7,6);
INSERT INTO District VALUES(138,"Житомир, місто",8,6);
INSERT INTO District VALUES(139,"Житомирський район",9,6);
INSERT INTO District VALUES(140,"Коростенський район",10,6);
INSERT INTO District VALUES(141,"Коростишівський район",11,6);
INSERT INTO District VALUES(142,"Лугинський район",12,6);
INSERT INTO District VALUES(143,"Любарський район",13,6);
INSERT INTO District VALUES(144,"Малинський район",14,6);
INSERT INTO District VALUES(145,"Народицький район",15,6);
INSERT INTO District VALUES(146,"Новоград-Волинський район",16,6);
INSERT INTO District VALUES(147,"Овруцький район",17,6);
INSERT INTO District VALUES(148,"Олевський район",18,6);
INSERT INTO District VALUES(149,"Попільнянський район",19,6);
INSERT INTO District VALUES(150,"Радомишльський район",20,6);
INSERT INTO District VALUES(151,"Ружинський район",21,6);
INSERT INTO District VALUES(152,"Червоноармійський район",22,6);
INSERT INTO District VALUES(153,"Черняхівський район",23,6);
INSERT INTO District VALUES(154,"Чуднівський район",24,6);

# 7. Закарпатська область
INSERT INTO District VALUES(155,"Берегівський район",1,7);
INSERT INTO District VALUES(156,"Великоберезнянський район",2,7);
INSERT INTO District VALUES(157,"Виноградівський район",3,7);
INSERT INTO District VALUES(158,"Воловецький район",4,7);
INSERT INTO District VALUES(159,"Іршавський район",5,7);
INSERT INTO District VALUES(160,"Міжгірський район",6,7);
INSERT INTO District VALUES(161,"Мукачівський район",7,7);
INSERT INTO District VALUES(162,"Перечинський район",8,7);
INSERT INTO District VALUES(163,"Рахівський район",9,7);
INSERT INTO District VALUES(164,"Свалявський район",10,7);
INSERT INTO District VALUES(165,"Тячівський район",11,7);
INSERT INTO District VALUES(166,"Ужгород, місто",12,7);
INSERT INTO District VALUES(167,"Ужгородський район",13,7);
INSERT INTO District VALUES(168,"Хустський район",14,7);
INSERT INTO District VALUES(169,"Чоп, місто",15,7);

# 8. Запорізька область
INSERT INTO District VALUES(170,"Бердянський район",1,8);
INSERT INTO District VALUES(171,"Василівський район",2,8);
INSERT INTO District VALUES(172,"Великобілозерський район",3,8);
INSERT INTO District VALUES(173,"Веселівський район",4,8);
INSERT INTO District VALUES(174,"Вільнянський район",5,8);
INSERT INTO District VALUES(175,"Гуляйпільський район",6,8);
INSERT INTO District VALUES(176,"Енергодар, місто",7,8);
INSERT INTO District VALUES(177,"Запоріжжя, місто",8,8);
INSERT INTO District VALUES(178,"Запорізький район",9,8);
INSERT INTO District VALUES(179,"Кам'янсько-Дніпровський район",10,8);
INSERT INTO District VALUES(180,"Куйбишевський район",11,8);
INSERT INTO District VALUES(181,"Мелітопольський район",12,8);
INSERT INTO District VALUES(182,"Михайлівський район",13,8);
INSERT INTO District VALUES(183,"Новомиколаївський район",14,8);
INSERT INTO District VALUES(184,"Оріхівський район",15,8);
INSERT INTO District VALUES(185,"Пологівський район",16,8);
INSERT INTO District VALUES(186,"Приазовський район",17,8);
INSERT INTO District VALUES(187,"Приморський район",18,8);
INSERT INTO District VALUES(188,"Розівський район",19,8);
INSERT INTO District VALUES(189,"Токмацький район",20,8);
INSERT INTO District VALUES(190,"Чернігівський район",21,8);
INSERT INTO District VALUES(191,"Якимівський район",22,8);

# 9. Івано-Франківська область
INSERT INTO District VALUES(192,"Богородчанський район",1,9);
INSERT INTO District VALUES(193,"Болехівський район",2,9);
INSERT INTO District VALUES(194,"Верховинський район",3,9);
INSERT INTO District VALUES(195,"Галицький район",4,9);
INSERT INTO District VALUES(196,"Городенківський район",5,9);
INSERT INTO District VALUES(197,"Долинський район",6,9);
INSERT INTO District VALUES(198,"Івано-Франківськ, місто",7,9);
INSERT INTO District VALUES(199,"Калуський район",8,9);
INSERT INTO District VALUES(200,"Коломийський район",9,9);
INSERT INTO District VALUES(201,"Косівський район",10,9);
INSERT INTO District VALUES(202,"Надвірнянський район",11,9);
INSERT INTO District VALUES(203,"Рогатинський район",12,9);
INSERT INTO District VALUES(204,"Рожнятівський район",13,9);
INSERT INTO District VALUES(205,"Снятинський район",14,9);
INSERT INTO District VALUES(206,"Тисменицький район",15,9);
INSERT INTO District VALUES(207,"Тлумацький район",16,9);
INSERT INTO District VALUES(208,"Яремча, місто",17,9);

# 11. Київська область
INSERT INTO District VALUES(209,"Баришівський район",1,11);
INSERT INTO District VALUES(210,"Білоцерквівський район",2,11);
INSERT INTO District VALUES(211,"Богуславський район",3,11);
INSERT INTO District VALUES(212,"Бориспільський район",4,11);
INSERT INTO District VALUES(213,"Бородянський район",5,11);
INSERT INTO District VALUES(214,"Броварський район",6,11);
INSERT INTO District VALUES(215,"Васильківський район",7,11);
INSERT INTO District VALUES(216,"Вишгородський район",8,11);
INSERT INTO District VALUES(217,"Володарський район",9,11);
INSERT INTO District VALUES(218,"Згурівський район",10,11);
INSERT INTO District VALUES(219,"Іванківський район",11,11);
INSERT INTO District VALUES(220,"Ірпінь, місто",12,11);
INSERT INTO District VALUES(221,"Кагарлицький район",13,11);
INSERT INTO District VALUES(222,"Києво-Святошинський район",14,11);
INSERT INTO District VALUES(223,"Макарівський район",15,11);
INSERT INTO District VALUES(224,"Миронівський район",16,11);
INSERT INTO District VALUES(225,"Обухівський район",17,11);
INSERT INTO District VALUES(226,"Переяслав-Хмельницький район",18,11);
INSERT INTO District VALUES(227,"Поліський район",19,11);
INSERT INTO District VALUES(228,"Рокитнянський район",20,11);
INSERT INTO District VALUES(229,"Сквирський район",21,11);
INSERT INTO District VALUES(230,"Славутич, місто",22,11);
INSERT INTO District VALUES(231,"Ставищенський район",23,11);
INSERT INTO District VALUES(232,"Таращанський район",24,11);
INSERT INTO District VALUES(233,"Тетіївський район",25,11);
INSERT INTO District VALUES(234,"Фастівський район",26,11);
INSERT INTO District VALUES(235,"Яготинський район",27,11);

# 12. Кіровоградська область
INSERT INTO District VALUES(236,"Бобринецький район",1,12);
INSERT INTO District VALUES(237,"Вільшанський район",2,12);
INSERT INTO District VALUES(238,"Гайворонський район",3,12);
INSERT INTO District VALUES(239,"Голованівський район",4,12);
INSERT INTO District VALUES(240,"Добровеличківський район",5,12);
INSERT INTO District VALUES(241,"Долинський район",6,12);
INSERT INTO District VALUES(242,"Знам'янський район",7,12);
INSERT INTO District VALUES(243,"Кіровоград, місто",8,12);
INSERT INTO District VALUES(244,"Кіровоградський район",9,12);
INSERT INTO District VALUES(245,"Компаніївський район",10,12);
INSERT INTO District VALUES(246,"Маловисківський район",11,12);
INSERT INTO District VALUES(247,"Новгородківський район",12,12);
INSERT INTO District VALUES(248,"Новоархангельський район",13,12);
INSERT INTO District VALUES(249,"Новомиргородський район",14,12);
INSERT INTO District VALUES(250,"Новоукраїнський район",15,12);
INSERT INTO District VALUES(251,"Олександрівський район",16,12);
INSERT INTO District VALUES(252,"Олександрійський район",17,12);
INSERT INTO District VALUES(253,"Онуфріївський район",18,12);
INSERT INTO District VALUES(254,"Петрівський район",19,12);
INSERT INTO District VALUES(255,"Світловодський район",20,12);
INSERT INTO District VALUES(256,"Ульяновський район",21,12);
INSERT INTO District VALUES(257,"Устинівський район",22,12);

# 13. Луганська область
INSERT INTO District VALUES(258,"Алчевськ, місто",1,13);
INSERT INTO District VALUES(259,"Антрацитівський район",2,13);
INSERT INTO District VALUES(260,"Біловодський район",3,13);
INSERT INTO District VALUES(261,"Білокуракинський район",4,13);
INSERT INTO District VALUES(262,"Брянка, місто",5,13);
INSERT INTO District VALUES(263,"Кіровськ, місто",6,13);
INSERT INTO District VALUES(264,"Краснодонський район",7,13);
INSERT INTO District VALUES(265,"Красний Луч, місто",8,13);
INSERT INTO District VALUES(266,"Кремінський район",9,13);
INSERT INTO District VALUES(267,"Лисичанськ, місто",10,13);
INSERT INTO District VALUES(268,"Луганськ, місто",11,13);
INSERT INTO District VALUES(269,"Лутугинський район",12,13);
INSERT INTO District VALUES(270,"Марківський район",13,13);
INSERT INTO District VALUES(271,"Міловський район",14,13);
INSERT INTO District VALUES(272,"Новоайдарський район",15,13);
INSERT INTO District VALUES(273,"Новопсковський район",16,13);
INSERT INTO District VALUES(274,"Первомайськ, місто",17,13);
INSERT INTO District VALUES(275,"Перевальський район",18,13);
INSERT INTO District VALUES(276,"Попаснянський район",19,13);
INSERT INTO District VALUES(277,"Ровеньки, місто",20,13);
INSERT INTO District VALUES(278,"Рубіжне, місто",21,13);
INSERT INTO District VALUES(279,"Сватівський район",22,13);
INSERT INTO District VALUES(280,"Свердловський район",23,13);
INSERT INTO District VALUES(281,"Сіверськодонецьк, місто",24,13);
INSERT INTO District VALUES(282,"Слов'яносербський район",25,13);
INSERT INTO District VALUES(283,"Станично-Луганський район",26,13);
INSERT INTO District VALUES(284,"Старобільський район",27,13);
INSERT INTO District VALUES(285,"Стаханов, місто",28,13);
INSERT INTO District VALUES(286,"Троїцький район",29,13);

# 14. Львівська область
INSERT INTO District VALUES(287,"Борислав, місто",1,14);
INSERT INTO District VALUES(288,"Бродівський район",2,14);
INSERT INTO District VALUES(289,"Буський район",3,14);
INSERT INTO District VALUES(290,"Городоцький район",4,14);
INSERT INTO District VALUES(291,"Дрогобицький район",5,14);
INSERT INTO District VALUES(292,"Жидачівський район",6,14);
INSERT INTO District VALUES(293,"Жовківський район",7,14);
INSERT INTO District VALUES(294,"Золочівський район",8,14);
INSERT INTO District VALUES(295,"Кам'янсько-Бузький",9,14);
INSERT INTO District VALUES(296,"Львів, місто",10,14);
INSERT INTO District VALUES(297,"Миколаївський район",11,14);
INSERT INTO District VALUES(298,"Мостиський район",12,14);
INSERT INTO District VALUES(299,"Перемишлянський район",13,14);
INSERT INTO District VALUES(300,"Пустомитівський район",14,14);
INSERT INTO District VALUES(301,"Радехівський район",15,14);
INSERT INTO District VALUES(302,"Самбірський район",16,14);
INSERT INTO District VALUES(303,"Сколівський район",17,14);
INSERT INTO District VALUES(304,"Сокальський район",18,14);
INSERT INTO District VALUES(305,"Старосамбірський район",19,14);
INSERT INTO District VALUES(306,"Стрийський район",20,14);
INSERT INTO District VALUES(307,"Трускавець, місто",21,14);
INSERT INTO District VALUES(308,"Турківський район",22,14);
INSERT INTO District VALUES(309,"Червоноград, місто",23,14);
INSERT INTO District VALUES(310,"Яворівський район",24,14);

# 15. Миколаївська область
INSERT INTO District VALUES(311,"Арбузинський район",1,15);
INSERT INTO District VALUES(312,"Баштанський район",2,15);
INSERT INTO District VALUES(313,"Березанський район",3,15);
INSERT INTO District VALUES(314,"Березнегуватський район",4,15);
INSERT INTO District VALUES(315,"Братський район",5,15);
INSERT INTO District VALUES(316,"Веселинівський район",6,15);
INSERT INTO District VALUES(317,"Вознесенський район",7,15);
INSERT INTO District VALUES(318,"Врадіївський район",8,15);
INSERT INTO District VALUES(319,"Доманівський район",9,15);
INSERT INTO District VALUES(320,"Єланецький район",10,15);
INSERT INTO District VALUES(321,"Жовтневий район",11,15);
INSERT INTO District VALUES(322,"Казанківський район",12,15);
INSERT INTO District VALUES(323,"Кривоозерський район",13,15);
INSERT INTO District VALUES(324,"Миколаїв, місто",14,15);
INSERT INTO District VALUES(325,"Миколаївський район",15,15);
INSERT INTO District VALUES(326,"Новобузький район",16,15);
INSERT INTO District VALUES(327,"Новоодеський район",17,15);
INSERT INTO District VALUES(328,"Очаківський район",18,15);
INSERT INTO District VALUES(329,"Первомайський район",19,15);
INSERT INTO District VALUES(330,"Снігурівський район",20,15);
INSERT INTO District VALUES(331,"Южноукраїнськ, місто",21,15);

# 16. Одеська область
INSERT INTO District VALUES(332,"Ананьївський район",1,16);
INSERT INTO District VALUES(333,"Арцизький район",2,16);
INSERT INTO District VALUES(334,"Балтський район",3,16);
INSERT INTO District VALUES(335,"Березівський район",4,16);
INSERT INTO District VALUES(336,"Білгород-Дністровський район",5,16);
INSERT INTO District VALUES(337,"Біляївський район",6,16);
INSERT INTO District VALUES(338,"Болградський район",7,16);
INSERT INTO District VALUES(339,"Великомихайлівський район",8,16);
INSERT INTO District VALUES(340,"Іванівський район",9,16);
INSERT INTO District VALUES(341,"Ізмаїльський район",10,16);
INSERT INTO District VALUES(342,"Іллічівськ, місто",11,16);
INSERT INTO District VALUES(343,"Кілійський район",12,16);
INSERT INTO District VALUES(344,"Кодимський район",13,16);
INSERT INTO District VALUES(345,"Комінтернівський район",14,16);
INSERT INTO District VALUES(346,"Котовський район",15,16);
INSERT INTO District VALUES(347,"Красноокнянський район",16,16);
INSERT INTO District VALUES(348,"Любашівський район",17,16);
INSERT INTO District VALUES(349,"Миколаївський район",18,16);
INSERT INTO District VALUES(350,"Овідіопольський район",19,16);
INSERT INTO District VALUES(351,"Одеса, місто",20,16);
INSERT INTO District VALUES(352,"Ренійський район",21,16);
INSERT INTO District VALUES(353,"Роздільнянський район",22,16);
INSERT INTO District VALUES(354,"Савранський район",23,16);
INSERT INTO District VALUES(355,"Саратський район",24,16);
INSERT INTO District VALUES(356,"Тарутинський район",25,16);
INSERT INTO District VALUES(357,"Татарбунарський район",26,16);
INSERT INTO District VALUES(358,"Фрунзівський район",27,16);
INSERT INTO District VALUES(359,"Ширяївський район",28,16);

# 17. Полтавська область
INSERT INTO District VALUES(360,"Великобагачанський район",1,17);
INSERT INTO District VALUES(361,"Гадяцький район",2,17);
INSERT INTO District VALUES(362,"Глобинський район",3,17);
INSERT INTO District VALUES(363,"Гребінківський район",4,17);
INSERT INTO District VALUES(364,"Диканський район",5,17);
INSERT INTO District VALUES(365,"Зіньківський район",6,17);
INSERT INTO District VALUES(366,"Карлівський район",7,17);
INSERT INTO District VALUES(367,"Кобеляцький район",8,17);
INSERT INTO District VALUES(368,"Козельщинський район",9,17);
INSERT INTO District VALUES(369,"Комсомольськ, місто",10,17);
INSERT INTO District VALUES(370,"Котелевський район",11,17);
INSERT INTO District VALUES(371,"Кременчук, місто",12,17);
INSERT INTO District VALUES(372,"Кременчуцький район",13,17);
INSERT INTO District VALUES(373,"Лохвицький район",14,17);
INSERT INTO District VALUES(374,"Лубенський район",15,17);
INSERT INTO District VALUES(375,"Машівський район",16,17);
INSERT INTO District VALUES(376,"Миргородський район",17,17);
INSERT INTO District VALUES(377,"Новосанжарський район",18,17);
INSERT INTO District VALUES(378,"Оржицький район",19,17);
INSERT INTO District VALUES(379,"Пирятинський район",20,17);
INSERT INTO District VALUES(380,"Полтава, місто",21,17);
INSERT INTO District VALUES(381,"Полтавський район",22,17);
INSERT INTO District VALUES(382,"Решетилівський район",23,17);
INSERT INTO District VALUES(383,"Семенівський район",24,17);
INSERT INTO District VALUES(384,"Хорольський район",25,17);
INSERT INTO District VALUES(385,"Чорнухинський район",26,17);
INSERT INTO District VALUES(386,"Чутівський район",27,17);
INSERT INTO District VALUES(387,"Шишацький район",28,17);

# 18. Рівненська область
INSERT INTO District VALUES(388,"Березнівський район",1,18);
INSERT INTO District VALUES(389,"Володимирецький район",2,18);
INSERT INTO District VALUES(390,"Гощанський район",3,18);
INSERT INTO District VALUES(391,"Демидівський район",4,18);
INSERT INTO District VALUES(392,"Дубнівський район",5,18);
INSERT INTO District VALUES(393,"Дубровицький район",6,18);
INSERT INTO District VALUES(394,"Зарічненський район",7,18);
INSERT INTO District VALUES(395,"Здолбунівський район",8,18);
INSERT INTO District VALUES(396,"Корецький район",9,18);
INSERT INTO District VALUES(397,"Костопільський район",10,18);
INSERT INTO District VALUES(398,"Кузнецовськ, місто",11,18);
INSERT INTO District VALUES(399,"Млинівський район",12,18);
INSERT INTO District VALUES(400,"Острозький район",13,18);
INSERT INTO District VALUES(401,"Радивилівський район",14,18);
INSERT INTO District VALUES(402,"Рівне, місто",15,18);
INSERT INTO District VALUES(403,"Рівненський район",16,18);
INSERT INTO District VALUES(404,"Рокитнівський район",17,18);
INSERT INTO District VALUES(405,"Сарненський район",18,18);

# 20. Сумська область
INSERT INTO District VALUES(406,"Білопільський район",1,20);
INSERT INTO District VALUES(407,"Буринський район",2,20);
INSERT INTO District VALUES(408,"Великописарівський район",3,20);
INSERT INTO District VALUES(409,"Глухівський район",4,20);
INSERT INTO District VALUES(410,"Конотопський район",5,20);
INSERT INTO District VALUES(411,"Краснопільський район",6,20);
INSERT INTO District VALUES(412,"Кролевецький район",7,20);
INSERT INTO District VALUES(413,"Лебединський район",8,20);
INSERT INTO District VALUES(414,"Липоводолинський район",9,20);
INSERT INTO District VALUES(415,"Недригайлівський район",10,20);
INSERT INTO District VALUES(416,"Охтирський район",11,20);
INSERT INTO District VALUES(417,"Путивльський район",12,20);
INSERT INTO District VALUES(418,"Роменський район",13,20);
INSERT INTO District VALUES(419,"Середино-Будський район",14,20);
INSERT INTO District VALUES(420,"Суми, місто",15,20);
INSERT INTO District VALUES(421,"Сумський район",16,20);
INSERT INTO District VALUES(422,"Тростянецький район",17,20);
INSERT INTO District VALUES(423,"Шосткинський район",18,20);
INSERT INTO District VALUES(424,"Ямпільський район",19,20);

# 21. Тернопільська область
INSERT INTO District VALUES(425,"Бережанський район",1,21);
INSERT INTO District VALUES(426,"Борщівський район",2,21);
INSERT INTO District VALUES(427,"Бучацький район",3,21);
INSERT INTO District VALUES(428,"Гусятинський район",4,21);
INSERT INTO District VALUES(429,"Заліщицький район",5,21);
INSERT INTO District VALUES(430,"Збаразький район",6,21);
INSERT INTO District VALUES(431,"Зборівський район",7,21);
INSERT INTO District VALUES(432,"Козівський район",8,21);
INSERT INTO District VALUES(433,"Кременецький район",9,21);
INSERT INTO District VALUES(434,"Лановецький район",10,21);
INSERT INTO District VALUES(435,"Монастириський район",11,21);
INSERT INTO District VALUES(436,"Підволочиський район",12,21);
INSERT INTO District VALUES(437,"Підгаєцький район",13,21);
INSERT INTO District VALUES(438,"Теребовлянський район",14,21);
INSERT INTO District VALUES(439,"Тернопіль, місто",15,21);
INSERT INTO District VALUES(440,"Тернопільський район",16,21);
INSERT INTO District VALUES(441,"Чортківський район",17,21);
INSERT INTO District VALUES(442,"Шумський район",18,21);

# 22. Харківська область
INSERT INTO District VALUES(443,"Балаклійський район",1,22);
INSERT INTO District VALUES(444,"Барвінківський район",2,22);
INSERT INTO District VALUES(445,"Близнюківський район",3,22);
INSERT INTO District VALUES(446,"Богодухівський район",4,22);
INSERT INTO District VALUES(447,"Борівський район",5,22);
INSERT INTO District VALUES(448,"Валківський район",6,22);
INSERT INTO District VALUES(449,"Великобурлуцький район",7,22);
INSERT INTO District VALUES(450,"Вовчанський район",8,22);
INSERT INTO District VALUES(451,"Дворічанський район",9,22);
INSERT INTO District VALUES(452,"Дергачівський район",10,22);
INSERT INTO District VALUES(453,"Зачепилівський район",11,22);
INSERT INTO District VALUES(454,"Зміївський район",12,22);
INSERT INTO District VALUES(455,"Золочівський район",13,22);
INSERT INTO District VALUES(456,"Ізюмський район",14,22);
INSERT INTO District VALUES(457,"Кегичівський район",15,22);
INSERT INTO District VALUES(458,"Коломацький район",16,22);
INSERT INTO District VALUES(459,"Красноградський район",17,22);
INSERT INTO District VALUES(460,"Краснокутський район",18,22);
INSERT INTO District VALUES(461,"Куп'янський район",19,22);
INSERT INTO District VALUES(462,"Лозівський район",20,22);
INSERT INTO District VALUES(463,"Нововодолазький район",21,22);
INSERT INTO District VALUES(464,"Первомайський район",22,22);
INSERT INTO District VALUES(465,"Печенізький район",23,22);
INSERT INTO District VALUES(466,"Сахновщинський район",24,22);
INSERT INTO District VALUES(467,"Харків, місто",25,22);
INSERT INTO District VALUES(468,"Харківський район",26,22);
INSERT INTO District VALUES(469,"Чугуївський район",27,22);
INSERT INTO District VALUES(470,"Шевченківський район",28,22);

# 23. Херсонська область
INSERT INTO District VALUES(471,"Бериславський район",1,23);
INSERT INTO District VALUES(472,"Білозерський район",2,23);
INSERT INTO District VALUES(473,"Великолепетиський район",3,23);
INSERT INTO District VALUES(474,"Великоолександрівський район",4,23);
INSERT INTO District VALUES(475,"Верхньорогачицький район",5,23);
INSERT INTO District VALUES(476,"Високопільський район",6,23);
INSERT INTO District VALUES(477,"Генічеський район",7,23);
INSERT INTO District VALUES(478,"Голопристанський район",8,23);
INSERT INTO District VALUES(479,"Горностаївський район",9,23);
INSERT INTO District VALUES(480,"Іванівський район",10,23);
INSERT INTO District VALUES(481,"Каланчацький район",11,23);
INSERT INTO District VALUES(482,"Каховський район",12,23);
INSERT INTO District VALUES(483,"Нижньосірогозький район",13,23);
INSERT INTO District VALUES(484,"Нова Каховка, місто",14,23);
INSERT INTO District VALUES(485,"Нововоронцовський район",15,23);
INSERT INTO District VALUES(486,"Новотроїцький район",16,23);
INSERT INTO District VALUES(487,"Скадовський район",17,23);
INSERT INTO District VALUES(488,"Херсон, місто",18,23);
INSERT INTO District VALUES(489,"Цюрупинський район",19,23);
INSERT INTO District VALUES(490,"Чаплинський район",20,23);

# 24. Хмельницька область
INSERT INTO District VALUES(491,"Білогірський район",1,24);
INSERT INTO District VALUES(492,"Віньковецький район",2,24);
INSERT INTO District VALUES(493,"Волочиський район",3,24);
INSERT INTO District VALUES(494,"Городоцький район",4,24);
INSERT INTO District VALUES(495,"Деражнянський район",5,24);
INSERT INTO District VALUES(496,"Дунаєвецький район",6,24);
INSERT INTO District VALUES(497,"Ізяславський район",7,24);
INSERT INTO District VALUES(498,"Кам'янець-Подільський район",8,24);
INSERT INTO District VALUES(499,"Красилівський район",9,24);
INSERT INTO District VALUES(500,"Летичівський район",10,24);
INSERT INTO District VALUES(501,"Нетішин, місто",11,24);
INSERT INTO District VALUES(502,"Новоушицький район",12,24);
INSERT INTO District VALUES(503,"Полонський район",13,24);
INSERT INTO District VALUES(504,"Славутський район",14,24);
INSERT INTO District VALUES(505,"Старокостянтинівський район",15,24);
INSERT INTO District VALUES(506,"Старосинявський район",16,24);
INSERT INTO District VALUES(507,"Теофіпольський район",17,24);
INSERT INTO District VALUES(508,"Хмельницький, місто",18,24);
INSERT INTO District VALUES(509,"Хмельницький район",19,24);
INSERT INTO District VALUES(510,"Чемеровецький район",20,24);
INSERT INTO District VALUES(511,"Шепетівський район",21,24);
INSERT INTO District VALUES(512,"Ярмолинецький район",22,24);

# 25. Черкаська область
INSERT INTO District VALUES(513,"Городищенський район",1,25);
INSERT INTO District VALUES(514,"Драбівський район",2,25);
INSERT INTO District VALUES(515,"Жашківський район",3,25);
INSERT INTO District VALUES(516,"Звенигородський район",4,25);
INSERT INTO District VALUES(517,"Золотоніський район",5,25);
INSERT INTO District VALUES(518,"Кам'янський район",6,25);
INSERT INTO District VALUES(519,"Канівський район",7,25);
INSERT INTO District VALUES(520,"Катеринопільський район",8,25);
INSERT INTO District VALUES(521,"Корсунь-Шевченківський район",9,25);
INSERT INTO District VALUES(522,"Лисянський район",10,25);
INSERT INTO District VALUES(523,"Маньківський район",11,25);
INSERT INTO District VALUES(524,"Монастирищенський район",12,25);
INSERT INTO District VALUES(525,"Смілянський район",13,25);
INSERT INTO District VALUES(526,"Тальнівський район",14,25);
INSERT INTO District VALUES(527,"Уманський район",15,25);
INSERT INTO District VALUES(528,"Христинівський район",16,25);
INSERT INTO District VALUES(529,"Черкаси, місто",17,25);
INSERT INTO District VALUES(530,"Черкаський район",18,25);
INSERT INTO District VALUES(531,"Чигиринський район",19,25);
INSERT INTO District VALUES(532,"Чорнобаївський район",20,25);
INSERT INTO District VALUES(533,"Шполянський район",21,25);

# 26. Чернівецька область
INSERT INTO District VALUES(534,"Вижницький район",1,26);
INSERT INTO District VALUES(535,"Герцаївський район",2,26);
INSERT INTO District VALUES(536,"Глибоцький район",3,26);
INSERT INTO District VALUES(537,"Заставнівський район",4,26);
INSERT INTO District VALUES(538,"Кельменецький район",5,26);
INSERT INTO District VALUES(539,"Кіцманський район",6,26);
INSERT INTO District VALUES(540,"Новоселицький район",7,26);
INSERT INTO District VALUES(541,"Путильський район",8,26);
INSERT INTO District VALUES(542,"Сокирянський район",9,26);
INSERT INTO District VALUES(543,"Сторожинецький район",10,26);
INSERT INTO District VALUES(544,"Хотинський район",11,26);
INSERT INTO District VALUES(545,"Чернівці, місто",12,26);

# 27. Чернігівська область
INSERT INTO District VALUES(546,"Бахмацький район",1,27);
INSERT INTO District VALUES(547,"Бобровицький район",2,27);
INSERT INTO District VALUES(548,"Борзнянський район",3,27);
INSERT INTO District VALUES(549,"Варвинський район",4,27);
INSERT INTO District VALUES(550,"Городнянський район",5,27);
INSERT INTO District VALUES(551,"Ічнянський район",6,27);
INSERT INTO District VALUES(552,"Козелецький район",7,27);
INSERT INTO District VALUES(553,"Коропський район",8,27);
INSERT INTO District VALUES(554,"Корюківський район",9,27);
INSERT INTO District VALUES(555,"Куликівський район",10,27);
INSERT INTO District VALUES(556,"Менський район",11,27);
INSERT INTO District VALUES(557,"Ніжинський район",12,27);
INSERT INTO District VALUES(558,"Новгород-Сіверський район",13,27);
INSERT INTO District VALUES(559,"Носівський район",14,27);
INSERT INTO District VALUES(560,"Прилуцький район",15,27);
INSERT INTO District VALUES(561,"Ріпкинський район",16,27);
INSERT INTO District VALUES(562,"Семенівський район",17,27);
INSERT INTO District VALUES(563,"Сосницький район",18,27);
INSERT INTO District VALUES(564,"Срібнянський район",19,27);
INSERT INTO District VALUES(565,"Талалаївський район",20,27);
INSERT INTO District VALUES(566,"Чернігів, місто",21,27);
INSERT INTO District VALUES(567,"Чернігівський район",22,27);
INSERT INTO District VALUES(568,"Щорський район",23,27);

# 10. Київ місто
INSERT INTO District VALUES(569,"Київ місто",1,10);

# 19. Севастополь місто
INSERT INTO District VALUES(570,"Севастополь місто",1,19);