# FILL REGIONS
INSERT INTO Region VALUES (1, "Автономна республіка Крим", 1);
INSERT INTO Region VALUES (2, "Вінницька область", 2);
INSERT INTO Region VALUES (3, "Волинська область", 3);
INSERT INTO Region VALUES (4, "Дніпропетровська область", 4);
INSERT INTO Region VALUES (5, "Донецька область", 5);
INSERT INTO Region VALUES (6, "Житомирська область", 6);
INSERT INTO Region VALUES (7, "Закарпатська область", 7);
INSERT INTO Region VALUES (8, "Запорізька область", 8);
INSERT INTO Region VALUES (9, "Івано-Франківська область", 9);
INSERT INTO Region VALUES (10, "Київ, місто", 10);
INSERT INTO Region VALUES (11, "Київська область", 11);
INSERT INTO Region VALUES (12, "Кіровоградська область", 12);
INSERT INTO Region VALUES (13, "Луганська область", 13);
INSERT INTO Region VALUES (14, "Львівська область", 14);
INSERT INTO Region VALUES (15, "Миколаївська область", 15);
INSERT INTO Region VALUES (16, "Одеська область", 16);
INSERT INTO Region VALUES (17, "Полтавська область", 17);
INSERT INTO Region VALUES (18, "Рівненська область", 18);
INSERT INTO Region VALUES (19, "Севастополь, місто", 19);
INSERT INTO Region VALUES (20, "Сумська область", 20);
INSERT INTO Region VALUES (21, "Тернопільська область", 21);
INSERT INTO Region VALUES (22, "Харківська область", 22);
INSERT INTO Region VALUES (23, "Херсонська область", 23);
INSERT INTO Region VALUES (24, "Хмельницька область", 24);
INSERT INTO Region VALUES (25, "Черкаська область", 25);
INSERT INTO Region VALUES (26, "Чернівецька область", 26);
INSERT INTO Region VALUES (27, "Чернігівська область", 27);